= Mule 4 OpenTelemetry (OTel) Agent Extension
// Document header
// Document header
Rick Bansal <rick.bansal@mulesoft.com>
:revnumber: 1.0.118-SNAPSHOT
:revdate: February 27, 2022
:revremark: Initial Draft
:doctype: book
:icons: font
:toc: left
:keywords: Mule, MuleSoft, Observability, OpenTelemetry, OTel, Tracing, Instrumentation, Distributed

// The following pass through will align the images and their titles
ifndef::env-github[]
++++
<style>
  .imageblock > .title {
    text-align: inherit;
    margin-top: 10px;
  }
</style>
++++
endif::[]

ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :heavy_exclamation_mark:
:note-caption: :information_source:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

//
// custom attributes
//
:html-previewer: https://htmlpreview.github.io/?
:html-version-of-README: https://github.com/rickbansal-mulesoft/otel-mule4-observability-agent/blob/main/target/generated-docs/README.html
:docs-dir: src/docs/asciidoc
:extension-jar-filepath: target/otel-mule4-observability-agent-{revnumber}-mule-plugin.jar

 
[IMPORTANT]
====
This work effort is a field extension; hence, it is delivered on an "*as-is*" basis.
Please refrain from contacting MuleSoft Support for technical support. Instead. use *GitHub 
Issues* to provide feedback, suggest enhancements or report a bug.


==== 
== Links to the documentation

Please refer to one of the two options below for extended documentation on this extension.

=== HTML Version - Recommended
The HTML version is usually more presentation friendly and *preferred* for viewing this documentation.

* {html-previewer}{html-version-of-README}[Extended Documentation in HTML format]

=== ADOC Version
The adoc version doesn't always render optimally in GitHub but if you have trouble with HTML then
use this link.

//* link:src/docs/asciidoc/README.adoc[Extended Documentation in adoc format]

* link:{docs-dir}/README.adoc[Extended Documentation in adoc format]

== Link to the Extension jar file

The latest version of the extension, `otel-mule4-observability-agent-{revnumber}-mule-plugin.jar` can be downloaded from link:{extension-jar-filepath}[here].

